# Generated by Django 4.2.7 on 2023-11-25 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount",
        ),
    ]
