# Generated by Django 4.2.7 on 2023-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("Age", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=255)),
                ("preference", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=2048)),
                ("tags", models.TextField()),
            ],
        ),
    ]
